apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: default
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://florensiahiro1_db_user:INTHend1@cluster0.dvh0z6y.mongodb.net/?appName=Cluster0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: diary-backend
  template:
    metadata:
      labels:
        app: diary-backend
    spec:
      containers:
        - name: backend
          image: hushfire/diary-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_URI
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"